name: "ESLint - Pluggable JavaScript linter"
description: "A pluggable and configurable linter tool for identifying and reporting on patterns in JavaScript. Maintain your code quality with ease."
url: http://eslint.org
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
permalink: /blog/:year/:month/:title
paginate: 25
gems:
    - jekyll-sitemap
